language: java
sudo: required
addons: 
 sonarcloud:
    organization: "oxygenxml-github"
    token:
      secure: "${SONAR_CLOUD_TOKEN}"
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - chmod +x travis/checkForTag.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${MY_GH_TOKEN_OXYGEN}:@github.com" > .git/credentials
  - ./travis/checkForTag.sh
script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${MY_GH_TOKEN_OXYGEN}
  file:
    - target/git.support-${TRAVIS_TAG}-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: true
  provider: nightly
  api_key: ${MY_GH_TOKEN_OXYGEN}
  file:
    - target/git.support-1.0.0-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: false
    
